### PR TITLE
Select all text in label on click to quickly replace it

### PR DESCRIPTION
**Pull request by ltGuillaume**

### CODE REVIEW

**Comment by tibbi** [comment]
I dont want to add that, there are many other fields the user might want to edit, not just the label

**Comment by ltGuillaume** [comment]
> 
> 
> I dont want to add that, there are many other fields the user might want to edit, not just the label

I think you misunderstand what this does. It doesn't autofocus the label field.

**Comment by tibbi** [comment]
right, I dont see the sense of selecting all either though

**Comment by ltGuillaume** [comment]
> 
> 
> right, I dont see the sense of selecting all either though

When you add a new alarm/timer, for some reason the label field is pre-filled with the previously used label. I don't understand the rationale behind that, since if keep adding alarms for the same occasion anyway, why label them at all? So imho the most intuitive thing to do is not to pre-fill the label field upon adding a new alarm/timer.

This PR would be to somewhat mitigate the annoyance of having to clear the label field every single time by backspacing the entire field or longpressing, before being able to enter the label you want.

**Pull request closed without merging**
