### PR TITLE
#fix160

### PR DESCRIPTION
**Pull request by coxtor**
Fixes issue #160

### CODE REVIEW

**Comment by tibbi** [comment]
use the code style used in the whole app please, do not introduce new style, formatting etc. And name your variables descriptively, not pi and mgr. Thanks

**Comment by tibbi** [comment]
I guess it will be ok with a couple changes, we will see. Thanks

**Comment by tibbi** [comment]
or nevermind, I reverted it. There were way too many unrelated things changed too in your fork. Please update only the relevant code.

**Comment by coxtor** [comment]
As far as I can see the pull request only targets three relevant files to fix the issue, am I missing something? The codebase should be on par with upstream.

**Comment by tibbi** [comment]
ye after creating a pull request on Github there is some text shown, how to test the changes on my pc before accepting it. But once I switched on your repo there was a huge amount of unrelated changes that also moved into Simple Clock after accepting it. Not sure why wasnt it shown at the pull request, but there was a lot of bad stuff.

**Comment by coxtor** [comment]
You should check out the branch #fix160 not master - that is my private build. When you compare/merge #fix160 with your upstream/master you will see that all my personal changes are not present. Maybe Githubs generated instructions are not correct.

**Comment by tibbi** [comment]
The trash files got included at accepting the pull request too. So you must have messed something up there.

**Comment by coxtor** [comment]
The comparison here [Comparison master  - fix160 ](https://github.com/SimpleMobileTools/Simple-Clock/compare/master...coxtor:%23fix160) clearly shows that only three files are affected within three commits. Do as you please.

**Comment by tibbi** [comment]
I cherry picked the fix with some tweaks. Thanks

**Pull request merged**
