### PR TITLE
Try reading stored timer in both obfuscated and non-obfuscated state

### PR DESCRIPTION
**Pull request by esensar**

### CODE REVIEW

**Comment by tibbi** [comment]
have you reproduced the issue? Was it obfuscated before and not anymore?

**Comment by esensar** [comment]
Yeah, in all previous versions it is stored obfuscated and due to some changes between the versions, the obfuscated names have changed for `TimerState`. Luckily, it is always `Idle` when stored in that field, so I just set it to default to `Idle` when reading from obfuscated state. Every new version will now write the `Timer` without obfuscation and it should be much easier to handle upgrades.

**Comment by tibbi** [comment]
alright thanks, hope it will work well. We want to store such stuff unobfuscated indeed

**Comment by esensar** [comment]
`Alarm` is still stored obfuscated. Should I do the same for it too?

**Comment by tibbi** [comment]
yeah, lets unobfuscate it, but properly handle updates too

**Pull request merged**
