### PR TITLE
Updated hr (Croatian) translation

### PR DESCRIPTION
**Pull request by Brane1003**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by tibbi** [comment]
please avoid creating new files and removing new lines, keep the same file structure. You should be translating files via Github, as described on https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file

**Comment by Brane1003** [comment]
Ok. Sorry for this. I'm new here :) Wont happen again.

**Comment by tibbi** [comment]
Ill cherry-pick the app title translation only. Thanks

**Comment by tibbi** [comment]
actually even that is too long, it can have max 50 characters

**Pull request closed without merging**
