### PR TITLE
Migrate to ViewPager2

### PR DESCRIPTION
**Pull request by Naveen3Singh**
### Notes:

- In the older ViewPager (thanks to android debugger), `onResume()` was called as soon as the fragment is created doesn't matter whether it's visible or not. **With ViewPager2, we have to ensure the views are set up properly in `onViewCreated()`** to avoid visible delays as [`onResume()`](https://github.com/xxv/android-lifecycle/blob/main/android-lifecycle-activity-to-fragments.png) is called at a later, perfectly valid, stage when the fragment is actually visible to the user. 
- As per [this page](https://developer.android.com/training/animation/vp2-migration), RTL paging is enabled automatically where appropriate based on locale (tested and works) but it's also possible to do so manually using `setLayoutDirection()`.

### CODE REVIEW

**Comment by tibbi** [comment]
tested on 11, swipe to the stopwatch tab and close the app for example

**Comment by Naveen3Singh** [comment]
Check pls. There shouldn't/won't be any more crashes/bugs

**Comment by Naveen3Singh** [comment]
apparently, there's no direct official API to do that, [google developers want us to use the fake dragging API](https://issuetracker.google.com/issues/122656759#comment3) (which internally scrolls the recycler view) and we'll accelerate, decelerate as needed.

[One solution is already available here](https://blog.birost.com/a?ID=01650-584ad12f-3cb3-43da-a0cf-8c115c0e700d), the summary is:
```kotlin
fun ViewPager2.setCurrentItem(
    item: Int,
    duration: Long,
    interpolator: TimeInterpolator = AccelerateDecelerateInterpolator(),
    pagePxWidth: Int = width
) {
    val pxToDrag: Int = pagePxWidth * (item - currentItem)
    val animator = ValueAnimator.ofInt(0, pxToDrag)
    var previousValue = 0
    animator.addUpdateListener { valueAnimator ->
        val currentValue = valueAnimator.animatedValue as Int
        val currentPxToDrag = (currentValue - previousValue).toFloat()
        fakeDragBy(-currentPxToDrag)
        previousValue = currentValue
    }
    animator.addListener(object : Animator.AnimatorListener {
        override fun onAnimationStart(animation: Animator?) {
            beginFakeDrag()
        }

        override fun onAnimationEnd(animation: Animator?) {
            endFakeDrag()
        }

        override fun onAnimationCancel(animation: Animator?) {}
        override fun onAnimationRepeat(animation: Animator?) {}
    })
    animator.interpolator = interpolator
    animator.duration = duration
    animator.start()
}
```

Fake dragging works fine (have done it before) as long as it's done correctly. Will try this :arrow_up: .

**Comment by Naveen3Singh** [comment]
Duration set to 300 ms:



Should I speed it up even more?

**Comment by tibbi** [comment]
Im not sure how many ms should it be, just compare it with the previous implementation.

**Comment by tibbi** [comment]
this is getting way too hacky, thought it will be simpler. Does it have any benefits over VIewPager 1 at all?

**Comment by Naveen3Singh** [comment]
Sorry, I force-pushed accidentally (the touchpad is going whacky, disabled it now)

Benefits of ViewPager2 as per the docs:
https://developer.android.com/training/animation/vp2-migration#benefits

major offers are: RTL support and RecyclerView related features like DiffUtil, and the ability to update fragment collections using notifyDatasetChanged()

**Comment by Naveen3Singh** [comment]
not sure why they chose to go with a long scroll duration but other than that, ViewPager2 complexity is comparable to ViewPager

**Comment by tibbi** [comment]
well, sadly this just doesnt work well. No matter what time I set or do, it is never smooth enough. Lets postpone it until it is actually  worth upgrading to ViewPager2. Thanks though

**Pull request closed without merging**
