### PR TITLE
Vibration fixes

### PR DESCRIPTION
**Pull request by rawlin**
Fixed issues with vibration in notifications as well as RemiderActivity

### CODE REVIEW

**Comment by tibbi** [comment]
it always vibrates to me on the lockscreen, even if it is disabled and change the audio file to create a new notification channel

**Comment by rawlin** [comment]
Added post delay for vibrations, and deleting notification channels after the notification is dismissed

**Comment by tibbi** [comment]
it still always vibrates to me on lockscreen. But if you cannot solve it, Ill just accept it as these issues can be system specific too

**Comment by rawlin** [comment]
> it still always vibrates to me on lockscreen. But if you cannot solve it, Ill just accept it as these issues can be system specific too

Sure @tibbi , I've tested this on 2 of my devices (Samsung Note 9 - Android 9 & Xiaomi Redmi Note 9 - Android 11) and these changes fix it for me

**Comment by tibbi** [comment]
dont you have some newer Android devices too? Testing it on 11 the highest isnt really a good idea

**Comment by rawlin** [comment]
@tibbi I usually test out features with emulators for the latest SDK versions but I don't believe there is a way to debug vibrations on an emulator so I used a physical device

**Comment by tibbi** [comment]
right, having Android 11 as the latest device is a pretty big limitation for the project though :/

**Comment by rawlin** [comment]
I'll install a custom rom of Android 13 if that's the case

**Comment by tibbi** [comment]
well, you should definitelybe using some newer OS for your own sake, so that you are familiar with the latest UI, animations, behaviour etc

**Comment by rawlin** [comment]
I've tested this on Samsung Note 9 on Android 13, and the vibration is working as expected on the lock screen with these changes

**Comment by tibbi** [comment]
okay thanks, will see how will it work to the users

**Pull request merged**
